openapi: 3.0.0
info:
  description: This is a library API
  version: 1.0.0
  title: Library
  license:
    name: Apache-2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: Witaxi Api
    description: This is the Witaxi Api.
paths:
  /api/auth/register:
    post:
      tags:
        - Register-Customer
      summary: Register a customer
      operationId: registerCustomer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterCustomerRequest'
      responses:
        "201":
          $ref: '#/components/responses/RegisterCustomerResponse'
        "422":
          description: Unprocessable Entity
components:
  schemas:
    RegisterCustomerRequest:
        title: Register Customer Request
        description: Object containing all the info needed to register a customer
        type: object
        required:
            - first_name
            - last_name
            - email
            - password
            - confirm_password
            - password
        properties:
            first_name: {type: string}
            last_name: {type: string}
            email: {type: string, format: email}
            phone: {type: string}
            password: {type: string, minLength: 8}
            confirm_password: {type: string, minLength: 8}
            role: {type: string}
            device_id: {type: string}
            device_type: {type: string}
            os_version: {type: string}
            fcm_token: {type: string, required: false}
    RegisterCustomerResponse:
      title: Register Customer Response
      description: Object containing the response of the register customer request
      type: object
      properties:
          registrationId: {type: string}
  responses:
    RegisterCustomerResponse:
      description: Session created successfully
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RegisterCustomerResponse'



